---
- name: Config Consul Servers
  hosts: servers
  vars_files:
    - vars/basic.yml
  tasks:
  - name: Deploy basic config file to run a 3 node cluster
    template:
      src: templates/consul-server-basic.hcl.j2
      dest: /etc/consul.d/consul.hcl
    when: (basic|bool)
    notify: restart consul

  - name: Deploy gossip config file to run a 3 node cluster
    template:
      src: templates/consul-server-gossip.hcl.j2
      dest: /etc/consul.d/consul.hcl
    when: (gossip|bool)
    notify: restart consul

  - name: Deploy tls configiuration on 3 node cluster
    block:
    - name: Ensure /etc/ssl/consul directory is present
      file:
        path: /etc/ssl/consul
        state: directory
        owner: consul
        group: consul
        mode: 0750

    - name: Copy ca file
      copy:
        src: /home/devops/files/consul_certs/consul-agent-ca.pem
        dest: /etc/ssl/consul/consul-agent-ca.pem
        owner: consul
        group: consul
        mode: 0640
           
    - name: Copy ca key file
      copy:
        src: /home/devops/files/consul_certs/consul-agent-ca-key.pem
        dest: /etc/ssl/consul/consul-agent-ca-key.pem
        owner: consul
        group: consul
        mode: 0640

    - name: Copy cert file
      copy:
        src: /home/devops/files/consul_certs/home-dc-server-consul-0.pem
        dest: /etc/ssl/consul/home-dc-server-consul-0.pem
        owner: consul
        group: consul
        mode: 0640

    - name: Copy cert key file
      copy:
        src: /home/devops/files/consul_certs/home-dc-server-consul-0-key.pem
        dest: /etc/ssl/consul/home-dc-server-consul-0-key.pem
        owner: consul
        group: consul
        mode: 0640

    - name: Deploy config file
      template:
        src: templates/consul-server-tls.hcl.j2
        dest: /etc/consul.d/consul.hcl
      notify: restart consul

    when: (tls|bool)

  - name: Start and enable consul service
    service:
      name: consul
      state: started
      enabled: true

  handlers:
  - name: restart consul
    service:
      name: consul
      state: restarted

