---
- name: Install basic packages on managed hosts
  hosts: all
  tasks:
  - name: Update all installed packages in managed hosts - RedHat Family Distribution
    yum:
      name: '*' 
      state: latest
    when: ansible_facts['distribution'] == "RedHat" 

  - name: Update all installed packages in managed hosts - Debian Family Distribution
    apt:
      name: '*'
      state: latest
    when: ansible_facts['distribution'] == "Debian" 
