---
- name: Set hostname as inventory
  hosts: all
  tasks:
  - name: Set hostname
    hostname:
      name: "{{ inventory_hostname }}"

  - name: Corrections on /etc/hosts
    lineinfile:
      path: /etc/hosts
      regexp: '^127\.0\.1\.1'
      line: "127.0.1.1  {{ inventory_hostname }}  {{ inventory_hostname_short }}" 
      owner: root
      group: root
      mode: '0644'


