---
- name: Install and configure node_exporter on managed hosts
  hosts: all
  remote_user: devops

  tasks:
  - name: Create user node_exporter
    user:
      name: node_exporter
      shell: /bin/false

  - name: Deploy node_exporter on managed host
    copy:
      src: /home/devops/files/node_exporter
      dest: /usr/local/bin
      owner: node_exporter
      group: node_exporter
      mode: 0755

  - name: Copy systemd file
    copy:
      src: files/node_exporter.service
      dest: /etc/systemd/system/node_exporter.service

  - name: Start and enable node_exporter service
    service:
      name: node_exporter
      state: started
      enabled: true

  - name: Node_exporter firewall rules
    firewalld:
      port: 9100/tcp
      permanent: true
      state: enabled
      immediate: true
    when: ansible_facts['distribution'] == "RedHat"


