---
- name: Basic configuration to vim
  hosts: all
  vars_files:
    - vars/users.yml
  tasks:
  - name: Template ~/.vimmc file - {{ users }}
    template:
      src: templates/vimrc.j2
      dest: "/home/{{ item }}/.vimrc"
      owner: "{{ item }}"
      group: "{{ item }}"
    loop: "{{ users }}"  

  - name: template /root/.vimrc
    template:
      src: templates/vimrc.j2
      dest: /root/.vimrc


